[package]
name = "tree_inspector"
version = "0.0.0"
edition = "2021"
authors = ["Pig Fang <g-plane@hotmail.com>"]
repository = "https://github.com/g-plane/pretty_graphql"
license = "MIT"
publish = false

[dependencies]
apollo-parser = "0.8"
