[book]
title = "Pretty GraphQL Documentation"
authors = ["Pig Fang"]
language = "en"

[output.html]
git-repository-url = "https://github.com/g-plane/pretty_graphql"
edit-url-template = "https://github.com/g-plane/pretty_graphql/edit/main/docs/{path}"
