name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - run: |
          cargo build --release -p dprint_plugin_graphql --target wasm32-unknown-unknown
          cp target/wasm32-unknown-unknown/release/dprint_plugin_graphql.wasm dprint_plugin/deployment/plugin.wasm
      - name: Publish dprint plugin
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dprint_plugin/deployment/plugin.wasm
            dprint_plugin/deployment/schema.json
      - uses: rust-lang/crates-io-auth-action@v1
        id: cratesio-auth
      - name: Publish crates
        run: cargo publish -p pretty_graphql
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.cratesio-auth.outputs.token }}
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Publish npm package
        run: |
          cp target/wasm32-unknown-unknown/release/dprint_plugin_graphql.wasm dprint_plugin/deployment/npm/plugin.wasm
          cd dprint_plugin/deployment/npm
          npm install -g npm@latest
          npm publish
